# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tc_pb2 as tc__pb2


class GetClassifierStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TextClassify = channel.unary_unary(
        '/GetClassifier/TextClassify',
        request_serializer=tc__pb2.Data.SerializeToString,
        response_deserializer=tc__pb2.Reply.FromString,
        )


class GetClassifierServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def TextClassify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GetClassifierServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TextClassify': grpc.unary_unary_rpc_method_handler(
          servicer.TextClassify,
          request_deserializer=tc__pb2.Data.FromString,
          response_serializer=tc__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'GetClassifier', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
